[package]
name = "atsame54_xpro"
version = "0.1.1"
authors = [
    "Karsten Große <karsten.grosse@sympatron.de>"
]
description = "Board Support crate for the SAM E54 Xplained Pro Evaluation Kit"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"

[dependencies]
cortex-m = "0.6"
embedded-hal = "0.2.3"
smart-leds = "0.3"
ws2812-spi = "0.2.0"
nb = "0.1"
generic-array = "0.14.4"

[dependencies.cortex-m-rt]
version = "0.6.12"
optional = true

[dependencies.atsamd-hal]
path = "../../hal"
version = "0.11"
default-features = false

[dependencies.usb-device]
version = "0.2"
optional = true

[dependencies.usbd-serial]
version = "0.1"
optional = true

[dependencies.ws2812-timer-delay]
version = "0.3"

[dependencies.smoltcp]
version = "*"
optional = true
default-features = false
features = ["ethernet", "proto-ipv4"]

[dev-dependencies]
panic-halt = "0.2"
# panic-semihosting = "0.5"
cortex-m-semihosting = "0.3"
smart-leds = "0.3"
ws2812-spi = "0.2.0"
cortex-m-rtic = "0.5.1"
# panic_rtt = "0.2"

[features]
default = ["rt", "atsamd-hal/same54p", "atsamd-hal/unproven", "smoltcp"]
rt = ["cortex-m-rt", "atsamd-hal/same54p-rt"]
unproven = ["atsamd-hal/unproven"]
usb = ["atsamd-hal/usb", "usb-device", "usbd-serial"]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = true

[profile.release]
lto = true
opt-level = "s"

[[example]]
name = "blinky_basic"

[[example]]
name = "smoltcp"
required-features = ["smoltcp"]
